### ISSUE TITLE
Could the CPI automatically assign dynamic public IPs?

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-azure-cpi-release#217]
We're noticing problems with the azure SNAT, and also anticipate issues when we have many diego cells in a single availability set all making outgoing connections (port exhaustion and delays allocating more ports).  It's very difficult to switch to using public IPs, because Azure requires us to precreate them and allocate them.  We're currently blocked on releasing PCF for azure until we have a solution for this SNAT problem, and using PIPs would be the best way to work around all these issues.

If the CPI had an optional feature to create an ephemeral (dynamic) public IP as a `vm_type` option, that would solve this for us.  It would also match options that exist in google and AWS CPIs, where it's trivial to assign a "random" public IP for a VM for outgoing traffic.  Something like this:

```
resource_pools:
- name: default
  cloud_properties:
    assign_dynamic_public_ips: true   # defaults to false
```

I think you could implement this by creating a PIP when you create the NIC for the VM, and delete that PIP when the NIC is deleted.

**Comment by gossion** [comment]
Because a VM can't have multiple public IPs, so we change "assign_dynamic_public_ips" to "assign_dynamic_public_ip".  Definition of resource_pools like this:
```
resource_pools:
- name: default
  cloud_properties:
    assign_dynamic_public_ip: true   # defaults to false
```
