### ISSUE TITLE
VM availability set on LB

### ISSUE THREAD

**Issue by pdelagrave** [cloudfoundry-incubator/bosh-azure-cpi-release#265]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 23
BOSH     Version: 261.4.0
OpsManager 1.10.4
ERT 1.10.7 stemcell 3363.20

Director stemcell:
bosh-azure-hyperv-ubuntu-trusty-go_agent
3363.15

### Environment
- Azure Environment:
  - [x ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: east-us
- Subscription ID: 52641c3e-894d-443e-b78b-e00305c8e021
- Resource Group Name: pcf-1-10-azure-clean-pcf-resource-group

### Issue Details
Deploying ERT using 3 tcp router VMs and one load balancer

OpsManager 1.10.4
ERT 1.10.7 stemcell 3363.20

The azure LB was created minutes before using terraform specifically for this environment and for the tcp router, it was not associated with any VMs prior running apply-changes.

We created dozen of exactly similar environments (LB and tcp_router setup) using the same scripts but it's the first time it fails that way.

### Logs (*Please redact all sensitive information in your logs*)
```
Started creating missing vms > tcp_router/75778d57-af18-4650-86b6-dee3f0434ea5 (0)
     Done creating missing vms > diego_cell/a322d973-696e-4a91-ac0d-081819ef7e42 (0) (00:01:58)
  Started creating missing vms > tcp_router/2581da30-6507-41cf-976b-3c066cdc54fd (1)
     Done creating missing vms > diego_brain/3960e41d-7a58-4186-a573-6480b5a59297 (2) (00:02:08)
  Started creating missing vms > tcp_router/eaae3e11-0980-4efd-bc09-cab90cf5c39d (2)
     Done creating missing vms > diego_cell/c64dbb6b-5afe-47f1-97d7-9d7467d97319 (2) (00:01:46)
     Done creating missing vms > diego_brain/6db53340-e034-495a-a7ba-2f8d775e2c27 (1) (00:02:16)
   Failed creating missing vms > tcp_router/2581da30-6507-41cf-976b-3c066cdc54fd (1): CPI error 'Bosh::Clouds::CloudError' with message 'http_get_response - #<Bosh::AzureCloud::AzureError: http_get_response - http code: 200
x-ms-client-request-id: e8e1e06a-50c6-437d-b185-7014c1b7652b
x-ms-request-id: 250274c0-8ac2-4f1a-9bd4-ec3de1df12b8
x-ms-correlation-request-id: e279e917-7bf9-42c7-8df5-bc8f002e1c48
x-ms-routing-request-id: EASTUS:20170502T185619Z:e279e917-7bf9-42c7-8df5-bc8f002e1c48
Error message: {
  "startTime": "2017-05-02T18:56:15.4809154+00:00",
  "endTime": "2017-05-02T18:56:15.8247998+00:00",
  "status": "Failed",
  "error": {
    "code": "VmIsNotInSameAvailabilitySetAsLb",
    "message": "Virtual Machine /subscriptions/52641c3e-894d-443e-b78b-e00305c8e021/resourceGroups/pcf-1-10-azure-clean-pcf-resource-group/providers/Microsoft.Compute/virtualMachines/787b414293boshvms2-c1033840-1627-41df-a15a-3b13104aa24e is using different Availability Set than other Virtual Machines connected to the Load Balancer(s) pcf-1-10-azure-clean-tcp-lb."
  },
  "name": "be452438-0e0f-4714-bb77-723527494b28"
}>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1847:in `http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1925:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2054:in `http_delete'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:544:in `delete_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:91:in `rescue in create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:17:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:164:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:125:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method (00:00:23)
     Done creating missing vms > doppler/038d91ae-e663-45bf-8ba8-84297bacd427 (1) (00:01:33)
   Failed creating missing vms > tcp_router/eaae3e11-0980-4efd-bc09-cab90cf5c39d (2): CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<Bosh::Clouds::CloudError: http_get_response - #<Bosh::AzureCloud::AzureError: http_get_response - http code: 200
x-ms-client-request-id: d063d8f1-2b3e-4d1b-a3b1-ab49e55ffd43
x-ms-request-id: 2e3c7f32-340e-48d7-b8b6-53b8cfd783f8
x-ms-correlation-request-id: 2c102ff9-2460-4a33-8cd7-890aeb9fea33
x-ms-routing-request-id: EASTUS:20170502T185614Z:2c102ff9-2460-4a33-8cd7-890aeb9fea33
Error message: {
  "startTime": "2017-05-02T18:56:10.119391+00:00",
  "endTime": "2017-05-02T18:56:10.7289822+00:00",
  "status": "Failed",
  "error": {
    "code": "VmIsNotInSameAvailabilitySetAsLb",
    "message": "Virtual Machine /subscriptions/52641c3e-894d-443e-b78b-e00305c8e021/resourceGroups/pcf-1-10-azure-clean-pcf-resource-group/providers/Microsoft.Compute/virtualMachines/787b414293boshvms1-d4a38a30-62bb-4fa4-9371-ff0dd0e47fdf is using different Availability Set than other Virtual Machines connected to the Load Balancer(s) pcf-1-10-azure-clean-tcp-lb."
  },
  "name": "2a0fc4c4-08ed-43a9-88ff-6f689ed3a7f9"
}>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1847:in `http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1925:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1995:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:322:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:86:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:164:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:125:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/helpers.rb:140:in `cloud_error'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1889:in `rescue in http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1814:in `http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1925:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1995:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:322:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:86:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:164:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:125:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method (00:00:34)
     Done creating missing vms > doppler/3dd48eea-f920-47cd-8a8a-9110a7dcf3b3 (0) (00:01:56)
     Done creating missing vms > diego_cell/e932da7b-be69-4378-a182-186f21f88b8b (1) (00:02:16)
     Done creating missing vms > loggregator_trafficcontroller/494203cc-4b51-4093-87b5-9cef9b32276c (1) (00:02:04)
     Done creating missing vms > loggregator_trafficcontroller/70de99e0-a50b-4db8-a266-f60f07b62516 (0) (00:02:13)
     Done creating missing vms > tcp_router/75778d57-af18-4650-86b6-dee3f0434ea5 (0) (00:01:47)
   Failed creating missing vms (00:10:42)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'http_get_response - #<Bosh::AzureCloud::AzureError: http_get_response - http code: 200
x-ms-client-request-id: e8e1e06a-50c6-437d-b185-7014c1b7652b
x-ms-request-id: 250274c0-8ac2-4f1a-9bd4-ec3de1df12b8
x-ms-correlation-request-id: e279e917-7bf9-42c7-8df5-bc8f002e1c48
x-ms-routing-request-id: EASTUS:20170502T185619Z:e279e917-7bf9-42c7-8df5-bc8f002e1c48
Error message: {
  "startTime": "2017-05-02T18:56:15.4809154+00:00",
  "endTime": "2017-05-02T18:56:15.8247998+00:00",
  "status": "Failed",
  "error": {
    "code": "VmIsNotInSameAvailabilitySetAsLb",
    "message": "Virtual Machine /subscriptions/52641c3e-894d-443e-b78b-e00305c8e021/resourceGroups/pcf-1-10-azure-clean-pcf-resource-group/providers/Microsoft.Compute/virtualMachines/787b414293boshvms2-c1033840-1627-41df-a15a-3b13104aa24e is using different Availability Set than other Virtual Machines connected to the Load Balancer(s) pcf-1-10-azure-clean-tcp-lb."
  },
  "name": "be452438-0e0f-4714-bb77-723527494b28"
}>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1847:in `http_get_response'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1925:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2054:in `http_delete'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:544:in `delete_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:91:in `rescue in create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:17:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:164:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:125:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method
```

### Repro steps (*if necessary, delete otherwise*)
1. First time happening, not sure if we can reproduce yet.
2.
3.
4.
5.

**Comment by AbelHu** [comment]
@pdelagrave Please check whether the 3 tcp router VMs belong to the same availability set. According to the error message, they should belong to at least 2 different availability sets. If you can reproduce it, you can update your `bosh.yml` to keep the failed VMs for later investigation.

```
      director:
        debug:
          keep_unreachable_vms: true
 ```

**Comment by pdelagrave** [comment]
Hi
I found the smallest possible setup to reproduce the bug. So far I've reproduced it with the version 23 and 24 of the CPI.
It might take a few tries to reproduce it, only the last 3 lines of the script have to be repeated to reproduce.

Replace the REPLACE_ME values in this script and in `params.json`

```bash
azure group create astest westus

azure group deployment create astest astest-deployment --template-uri https://raw.githubusercontent.com/azure/azure-quickstart-templates/master/bosh-setup/azuredeploy.json -e params.json

azure network public-ip create astest lbip westus
azure network lb create astest astest-lb westus
azure network lb frontend-ip create astest astest-lb feip -i lbip
azure network lb address-pool create astest astest-lb backendpool
azure network lb probe create astest astest-lb probe
azure network lb rule create astest astest-lb rule -f 2001 -b 2001 -t feip -o backendpool -e false

# LOGIN on the jumpbox
# ssh johnsmith@jumpbox-???.westus.cloudapp.azure.com
# scp the necessary files there: cc.yml, deployment.yml
# All the following commands are to be executed on the jumpbox

# download bosh cli v2
wget -O bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.16-linux-amd64
chmod +x bosh
sudo mv bosh /usr/local/bin

git clone https://github.com/cloudfoundry/bosh-deployment
# edit bosh-deployment/azure/cpi.yml to set the cpi version you want:
# version 23: ebf77f4b0d477fc9659d8de559c50afeec12c964
# version 24: 9f4cf9611c479f37b852ae2b33398753709d7027

bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/azure/cpi.yml \
    -v director_name=astest_bosh-1 \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.6 \
    -v vnet_name=boshvnet-crp \
    -v subnet_name=Bosh \
    -v subscription_id=REPLACE_ME \
    -v tenant_id=REPLACE_ME \
    -v client_id=REPLACE_ME \
    -v client_secret=... \
    -v resource_group_name=astest \
    -v storage_account_name=REPLACE_ME \
    -v default_security_group=nsg-bosh
    
bosh alias-env bosh-1 -e 10.0.0.6 --ca-cert <(bosh int ./creds.yml --path /director_ssl/ca)

export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=`bosh int ./creds.yml --path /admin_password`
export BOSH_ENVIRONMENT=bosh-1

bosh upload-stemcell https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3363.20
bosh upload-release https://bosh.io/d/github.com/jamlo/jmeter-bosh-release?v=1.0.0

bosh -n update-cloud-config cc.yml

#### RUN THIS IN A LOOP TO EVENTUALLY REPRODUCE THE BUG: ####
bosh -e bosh-1 -n deploy -d cf deployment.yml
bosh -e bosh-1 -n delete-deployment -d cf
azure availset delete astest astest-bosh-1-cf-test -q
#### END OF LOOP ####
```
cc.yml:
```yaml
---
azs:
- name: 'null'
  cloud_properties: {}
networks:
- name: ert-network
  type: manual
  subnets:
  - dns:
    - 168.63.129.16
    range: 10.0.0.0/22
    gateway: 10.0.0.1
    azs:
    - 'null'
    cloud_properties:
      virtual_network_name: boshvnet-crp
      subnet_name: Bosh
    reserved:
    - 10.0.0.2-10.0.0.4
    - 10.0.0.112-10.0.3.254
    static:
    - 10.0.0.5
    - 10.0.0.6
    - 10.0.0.7
    - 10.0.0.8
    - 10.0.0.9
    - 10.0.0.10
    - 10.0.0.11
    - 10.0.0.12
    - 10.0.0.13
    - 10.0.0.42
    - 10.0.0.43
    - 10.0.0.44    
vm_types:
- name: Standard_F1s
  cloud_properties:
    instance_type: Standard_F1s
    root_disk:
      size: 19456
    ephemeral_disk:
      use_root_disk: true
    storage_account_name: "*default*"
    storage_account_max_disk_number: 150
- name: Standard_F4s
  cloud_properties:
    instance_type: Standard_F4s
    root_disk:
      size: 68608
    ephemeral_disk:
      use_root_disk: true
    storage_account_name: "*default*"
    storage_account_max_disk_number: 150
disk_types:
- name: '1024'
  disk_size: 1024
  cloud_properties: {}
compilation:
  workers: 4
  network: ert-network
  az: 'null'
  reuse_compilation_vms: true
  vm_type: Standard_F4s
  vm_extensions:
  - vm-extension-compilation
  
vm_extensions:
- name: public_ip
  cloud_properties:
    assign_dynamic_public_ip: true

- name: vm-extension-compilation
  cloud_properties:
    assign_dynamic_public_ip: true

- name: vm-extension-with-lb
  cloud_properties:
    load_balancer: astest-lb
    assign_dynamic_public_ip: false
```
deployment.yml:
```yaml
---
name: cf
director_uuid: 86c402a2-2c98-4ed1-8080-0e4bc3abbf93
releases:
- name: jmeter-tornado
  version: 1.0.0

stemcells:
- alias: bosh-azure-hyperv-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3363.20'

instance_groups:
- name: test
  azs:
  - 'null'
  instances: 3
  lifecycle: service
  jobs:
  - name: jmeter_worker
    release: jmeter-tornado
  vm_type: Standard_F1s
  stemcell: bosh-azure-hyperv-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  networks:
  - name: ert-network
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.0.42
    - 10.0.0.43
    - 10.0.0.44
  persistent_disk_type: '1024'
  vm_extensions:
  - vm-extension-with-lb
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: false
```
params.json:
```json
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "value": "jumpbox"
    },
    "adminUsername": {
      "value": "johnsmith"
    },
    "sshKeyData": {
      "value": "REPLACE_ME"
    },
    "environment": {
      "value": "AzureCloud"
    },
    "tenantID": {
      "value": "REPLACE_ME"
    },
    "clientID": {
      "value": "REPLACE_ME"
    },
    "clientSecret": {
      "value": "REPLACE_ME"
    },
    "autoDeployBosh": {
      "value": "disabled"
    },
    "boshVmSize": {
      "value": "Standard_D2_v2"
    }
  }
}
```
