### ISSUE TITLE
Not able to specify disk type for bosh ephemeral disk/os disk

### ISSUE THREAD

**Issue by pritishmishra** [cloudfoundry-incubator/bosh-azure-cpi-release#384]
While specifying a VM type in our cloud-config, we used to specify the ephemeral disk size only (as shown below). Thus, a bosh ephemeral disk was getting created as the data disk. Here, the bosh ephemeral disk was of type `Premium_LRS`. 
```
- cloud_properties:
    ephemeral_disk:
      size: 10240
    instance_type: Standard_B1ms
```

However, we wanted to avoid the creation of extra data disk and hence, decided to use the root disk. We changed the configuration as shown below.
```
- cloud_properties:
    root_disk:
      size: 10240
    ephemeral_disk:
      use_root_disk: true
    instance_type: Standard_B1ms
```
The default disk-type of the root disk is `Standard_LRS`. We wanted to change the disk-type to `Premium_LRS`. However, using `storage_account_type: Premium_LRS` doesn't work here. 

Are we missing something here? Can the disk type of the bosh ephemeral disk/OS disk not be changed?
