### ISSUE TITLE
cloudfoundry.blob.core.windows.net no longer exist as a DNS record at all

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry-incubator/bosh-azure-cpi-release#89]
The Azure storage cloudfoundry was deleted by someone. 
If you followed the template guidance to deploy dev-box, you need to update the link to all three releases in ~/bosh.yml manually.

```
----
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=253
  sha1: 940956a23b642af3bb24b3cac37c4da746d6f9a9
- name: bosh-azure-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-azure-cpi-release?v=7
  sha1: 8df7b79458335188a1ecab83cf5ef9a82366baeb
...

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3192
    sha1: d096582bddf1771df4194c795edf6a96b90c8190
  cloud_properties:
    instance_type: Standard_D1
```
